In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

visa_df=pd.read_csv("Visadataset.csv")
visa_df.head()

cat_columns=visa_df.select_dtypes(include='object').columns
num_columns=visa_df.select_dtypes(exclude='object').columns

In [5]:
# create a dataframe having some missing values

dict1={'Names':['Tarun','Krishna','Ganesh',None],'Age':[30,31,np.nan,32],'City':[None,'Hyd','Pune','Blr']}

df1=pd.DataFrame(dict1)
df1

Names   Age  City
0    Tarun  30.0  None
1  Krishna  31.0   Hyd
2   Ganesh   NaN  Pune
3     None  32.0   Blr

In [6]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [7]:
df1.to_csv('missing_value_data_1.csv',index=False)

In [9]:
dict2={'Names':['Tarun','Krishna','Ganesh',None],'Age':[30,31,None,32],'City':[None,'Hyd','Pune','Blr']}
df2=pd.DataFrame(dict2)
df2

Names   Age  City
0    Tarun  30.0  None
1  Krishna  31.0   Hyd
2   Ganesh   NaN  Pune
3     None  32.0   Blr

In [10]:
df2.dtypes

Names     object
Age      float64
City      object
dtype: object

In [13]:
dict3={'Names':['Tarun','Krishna','Ganesh',None],'Age':[30,31,None,'32'],'City':[None,'Hyd','Pune','Blr']}
df3=pd.DataFrame(dict3)
df3

Names   Age  City
0    Tarun    30  None
1  Krishna    31   Hyd
2   Ganesh  None  Pune
3     None    32   Blr

In [14]:
df3.dtypes

Names    object
Age      object
City     object
dtype: object

In [17]:
df3['Age']=df3['Age'].astype('int')

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

In [16]:
int('32')

32

In [25]:
dict4={'Names':['Tarun','Krishna','Ganesh',None],'Age':[30,31,'33','32'],'City':[None,'Hyd','Pune','Blr']}
df4=pd.DataFrame(dict4)
df4

Names Age  City
0    Tarun  30  None
1  Krishna  31   Hyd
2   Ganesh  33  Pune
3     None  32   Blr

In [26]:
df4.dtypes

Names    object
Age      object
City     object
dtype: object

In [20]:
df4['Age']=df4['Age'].astype('int')

In [21]:
df4.dtypes

Names    object
Age       int32
City     object
dtype: object

- If you want to change the data type of a column use astype

- But if a column has missing values astype will fail

In [27]:
dict5={'Names':['Tarun','Krishna','Ganesh',None],'Age':[30,31,np.nan,'32'],'City':[None,'Hyd','Pune','Blr']}
df5=pd.DataFrame(dict5)
df5

Names  Age  City
0    Tarun   30  None
1  Krishna   31   Hyd
2   Ganesh  NaN  Pune
3     None   32   Blr

In [28]:
df5['Age']=df5['Age'].astype('int')

ValueError: cannot convert float NaN to integer

In [ ]:
# df5: valueError: cannot convert float NaN to integer: missing value np.nan === 'int' or 'float'
# df3: TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
    # string, int, float
#NanType represent as None

In [2]:
import numpy as np
import pandas as pd
dict5={'Names':['Tarun','Krishna','Ganesh',None],'Age':[30,31,np.nan,'32'],'City':[None,'Hyd','Pune','Blr']}
df5=pd.DataFrame(dict5)
df5['Age']=df5['Age'].astype('int')

ValueError: cannot convert float NaN to integer

- np.nan represents only number, that number can be an int or can be a float

- None represents string, bytes, float and int

**Method-1**

In [3]:
import numpy as np
import pandas as pd
dict1={'Names':['Tarun','Krishna','Ganesh',None],'Age':[30,31,np.nan,'32'],'City':[None,'Hyd','Pune','Blr']}
df1=pd.DataFrame(dict1)
df1

Names  Age  City
0    Tarun   30  None
1  Krishna   31   Hyd
2   Ganesh  NaN  Pune
3     None   32   Blr

In [7]:
df1.isnull()

Names    Age   City
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [8]:
df1.isna()

Names    Age   City
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [10]:
df1.isnull().sum()
# It will give column wise missing values

Names    1
Age      1
City     1
dtype: int64

In [11]:
# The total values in first column are: 4
# In that 1 value is missed
# so what could be the percentage: 1/4=25%
df1.isnull().sum()/len(df1)

Names    0.25
Age      0.25
City     0.25
dtype: float64

**fillna**

In [15]:
df1.fillna(20)

Names Age  City
0    Tarun  30    20
1  Krishna  31   Hyd
2   Ganesh  20  Pune
3       20  32   Blr

In [16]:
df1['Names'].fillna('sakhi')

0      Tarun
1    Krishna
2     Ganesh
3      sakhi
Name: Names, dtype: object

In [21]:
df1['City'].fillna('Chennai')

# until we save we cannot see updated dataframe

0    Chennai
1        Hyd
2       Pune
3        Blr
Name: City, dtype: object

In [22]:
df1

Names  Age  City
0    Tarun   30  None
1  Krishna   31   Hyd
2   Ganesh  NaN  Pune
3     None   32   Blr

**Method-2**

- We have some methods

  - bfill

  - ffill

  - backfill

  - pad

In [23]:
df1.fillna(method='bfill')

C:\Users\User\AppData\Local\Temp\ipykernel_6112\2949398996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')


Names Age  City
0    Tarun  30   Hyd
1  Krishna  31   Hyd
2   Ganesh  32  Pune
3     None  32   Blr

- bfill means before pill

- It will fill with next value

In [24]:
import warnings
warnings.filterwarnings('ignore')

In [25]:
df1.fillna(method='bfill')

Names Age  City
0    Tarun  30   Hyd
1  Krishna  31   Hyd
2   Ganesh  32  Pune
3     None  32   Blr

In [26]:
df1.fillna(method='ffill')

Names Age  City
0    Tarun  30  None
1  Krishna  31   Hyd
2   Ganesh  31  Pune
3   Ganesh  32   Blr

In [27]:
df1.fillna(method='backfill')

Names Age  City
0    Tarun  30   Hyd
1  Krishna  31   Hyd
2   Ganesh  32  Pune
3     None  32   Blr

In [28]:
df1.fillna(method='pad')

Names Age  City
0    Tarun  30  None
1  Krishna  31   Hyd
2   Ganesh  31  Pune
3   Ganesh  32   Blr

- backfill=bfill

- ffill=pad

- one more argument is there it is axis

- by default axis = 0

- can you give axis = 1 and repeat bfill ffill

In [29]:
df1.fillna(method='bfill',axis=1)

Names   Age  City
0    Tarun    30  None
1  Krishna    31   Hyd
2   Ganesh  Pune  Pune
3       32    32   Blr

In [30]:
df1.fillna(method='ffill',axis=1)

Names     Age  City
0    Tarun      30    30
1  Krishna      31   Hyd
2   Ganesh  Ganesh  Pune
3     None      32   Blr

**Method-3**

- We are filling  the values randomly

- We can do a specific way to fill

- Mean

- Median

- Mode

In [31]:
df1.fillna(35)

Names Age  City
0    Tarun  30    35
1  Krishna  31   Hyd
2   Ganesh  35  Pune
3       35  32   Blr

In [34]:
import numpy as np
import pandas as pd
dict1={'Names':['Tarun','Krishna','Ganesh',None],'Age':[30,31,np.nan,32],'City':[None,'Hyd','Pune','Blr']}
df1=pd.DataFrame(dict1)
df1

Names   Age  City
0    Tarun  30.0  None
1  Krishna  31.0   Hyd
2   Ganesh   NaN  Pune
3     None  32.0   Blr

In [37]:
mean_age=df1['Age'].mean()
mean_age

31.0

In [42]:
df1['Age'].fillna(mean_age)

0    30.0
1    31.0
2    31.0
3    32.0
Name: Age, dtype: float64

**KNN imputer**

- KNN means: K Nearest Neighbours

- where k is a number

- Instead of taking all the numbers average

- It consider k neighbours

- How can we know about the Neighbours

- Based on distance metric we will calculatee the distances 

- User will decide how many neighbours need to choose

- k = hyper parameters

- if k=5 means, it will take top 5 neighbours, which means

- those 5 observations has less distance

- will calculate average of those observations values

- package name: sklearn

  - class name: preprocessing

    - method name: SS, MMS, PT

  - class name: Impute

    - method name: KNNImputer


In [55]:
df1

Names   Age  City
0    Tarun  30.0  None
1  Krishna  31.0   Hyd
2   Ganesh   NaN  Pune
3     None  32.0   Blr

In [59]:
import numpy as np
from sklearn.impute import KNNImputer
knn=KNNImputer(n_neighbors=5)
knn.fit_transform(df1[['Age']])

array([[30.],
       [31.],
       [31.],
       [32.]])

In [67]:
import numpy as np
from sklearn.impute import KNNImputer
data = np.array([[1, 2, np.nan], 
                 [3, 4, 3], 
                 [7, 6, np.nan], 
                 [np.nan, 8, 9]])
knn = KNNImputer(n_neighbors=1)
imputed_data = knn.fit_transform(data)
print(imputed_data)

[[1. 2. 3.]
 [3. 4. 3.]
 [7. 6. 9.]
 [7. 8. 9.]]
